### ISSUE TITLE
Display's not fit in simulator

### ISSUE THREAD

**Issue by zesicus** [JamalK/Swifty#3]
Don't know if it's good in xcode7.2, mine is 7.1

![123](https://cloud.githubusercontent.com/assets/12265313/11783514/b43230d4-a2b2-11e5-9d56-aa1f087f273d.jpg)

This is weird two black bars on the top and bottom, and the status bar is not on the original place.
Even set auto layout  it still doesn't work

And console shows "<UIVisualEffectView 0x7fc6d1551950> is being asked to animate its opacity. This will cause the effect to appear broken until opacity returns to 1."

How do I fix that?

**Comment by JamalK** [comment]
I'm sorry you're facing this issue. I coded this a year ago, and didn't maintain it, I will check this out soon, and see if I can fix it. Thank you for filing the issue.

**Comment by zesicus** [comment]
I have fixed this problem, your code is good!
Yes, maybe the IB is old for now, then I created a new project and redraw those components connected with the ViewController.swift then it worked! the black bars gone! 
Thought there's still a prompt of console but doesn't infect using ~

Thank for your project, it's really beautiful and helpful !! :]
